
server:
  port: 9000
spring:
  application:
    name: catalogue-service
  r2dbc:
    url: r2dbc:postgresql://localhost:6000/catalogue_service_db
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:6000/catalogue_service_db
    user: postgres
    password: postgres
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG